name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew jar

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t exercise1 .
